# Use postgres/example user/password credentials
services:

  db:
    image: postgres
    container_name: game-chooser-db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: game_chooser_db
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql
      - ${POSTGRES_DATA_PATH}/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    # set shared memory limit when using docker compose
    shm_size: 128mb

  adminer:
    image: adminer
    container_name: game-chooser-adminer
    restart: always
    ports:
      - 8018:8080
